### ISSUE TITLE
Mono.Debugging.VisualStudio dependency has unresolved project URL

### ISSUE THREAD

**Issue by ztzg** [xamarin/vs-mono-debugger-sample#7]
Hi,

The `Mono.Debugger.Sample` project references the `Mono.Debugging.VisualStudio` NuGet package, as well as a `Mono.Debugging.VisualStudio.dll` assembly.

That package's metadata advertises the following as its "Project URL":

https://github.com/xamarin/debugger-vs

but Github returns 404/Not Found for that location. Search engine results did not seem relevant.  Could somebody please clarify and/or please point me to the new location of that project? Thanks!

-D

**Comment by kzu** [comment]
That package comes from a currently private repository, which is why you
get a 404.

Thanks

**Comment by ztzg** [comment]
Hi Daniel,

Thank you for the clarification.  Is is reassuring to read that those binaries, which are also used by other projects, are indeed originating and published by Xamarin.  This helps.

Do you have plans to open the `debugger-vs` repository?

(I am looking at this from the perspective of Sine Nomine Associates—ask Miguel if unsure—and not knowing the direction of the project, or which protocols and/or modifications are contained therein, makes it difficult to recommend as a dependency as there is a practical impossibility to customize should the need arise.)

Thanks,
Damien Diederen

P.-S. — Here is an example of a downstream consumer:
https://github.com/GordianDotNet/VSMonoDebugger/tree/master/Mono.Debugging.VisualStudio.4.9.10-pre

**Comment by kzu** [comment]
I'm afraid that's a question for @migueldeicaza himself.

Thanks

**Comment by migueldeicaza** [comment]
My understranding is that the NuGet provides an API to the engine that we ship with VS.

We do not currently plan on distributing the source, but we can take this into consideration.
